/**
 * AWSECommerceServicePortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.amazon.webservices.AWSECommerceService;

public interface AWSECommerceServicePortType extends java.rmi.Remote {
    public void itemSearch(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String XMLEscaping, java.lang.String validate, com.amazon.webservices.AWSECommerceService.ItemSearchRequest shared, com.amazon.webservices.AWSECommerceService.ItemSearchRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void itemLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.ItemLookupRequest shared, com.amazon.webservices.AWSECommerceService.ItemLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void browseNodeLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.BrowseNodeLookupRequest shared, com.amazon.webservices.AWSECommerceService.BrowseNodeLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.BrowseNodesArrayHolder browseNodes) throws java.rmi.RemoteException;
    public void similarityLookup(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.SimilarityLookupRequest shared, com.amazon.webservices.AWSECommerceService.SimilarityLookupRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.ItemsArrayHolder items) throws java.rmi.RemoteException;
    public void cartGet(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.CartGetRequest shared, com.amazon.webservices.AWSECommerceService.CartGetRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartAdd(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.CartAddRequest shared, com.amazon.webservices.AWSECommerceService.CartAddRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartCreate(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.CartCreateRequest shared, com.amazon.webservices.AWSECommerceService.CartCreateRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartModify(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.CartModifyRequest shared, com.amazon.webservices.AWSECommerceService.CartModifyRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
    public void cartClear(java.lang.String marketplaceDomain, java.lang.String AWSAccessKeyId, java.lang.String associateTag, java.lang.String validate, java.lang.String XMLEscaping, com.amazon.webservices.AWSECommerceService.CartClearRequest shared, com.amazon.webservices.AWSECommerceService.CartClearRequest[] request, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.OperationRequestHolder operationRequest, com.amazon.webservices.AWSECommerceService._2011_08_01.holders.CartArrayHolder cart) throws java.rmi.RemoteException;
}
